### ISSUE TITLE
Error in chapter 4

### ISSUE THREAD

**Issue by dtaylortech** [fouldsy/azure-samples#5]
I get the below error when I run "python2.7 storage_queue_demo.py"

Traceback (most recent call last):
  File "storage_queue_demo.py", line 12, in <module>
    from azure.storage.queue import QueueService
ImportError: cannot import name QueueService

Is this caused by an update to azure? Everything else in the book has worked brilliantly so far.

**Comment by fouldsy** [comment]
Yes, there's been quite a change in the underlying Python SDKs (especially finally moving away from 2.7). The 2nd edition versions should work - https://github.com/fouldsy/azure-mol-samples-2nd-ed/tree/master/04

Note that it's a slightly different install first:

```
pip install --user azurerm azure-cosmosdb-table azure-storage-queue==2.1.0
```

The samples also changed a little in chapter 17 and then again in chapter 21.  The content in the book is still mostly all correct in the 1st edition, it's more the code samples behind the scenes. In chapters 4, 17, and 21 I was just providing code samples to try and make things easier, so although the book content is still valid, those samples have changed a little.

Let me know if you still have problems here in chapter 4 when you follow the steps and examples from the 2nd edition repo.

**Comment by ITOrNotToIT** [comment]
Thanks fouldsy. Unfortunately, I had to do more than just install the azure-storage-queue==2.1.0. I also had to modify the script as this issue https://github.com/MicrosoftDocs/azure-docs/issues/42228 reports that QueueService was renamed to QueueServiceClient. So I modified the corresponding line and everything worked. My results may be unique to me as one could definitely accuse me of now know what I'm doing with python and they wouldn't be wrong. Just saying what worked for me.

**Comment by arto-pihlaja** [comment]
Having multiple subscriptions may pose problems. I was unable to run the scripts. With some debugging, I found out that the CLI was running in a subscription for which I wasn't authorized to create resource groups. I then hard coded the right subscription into the script. Another way would be to switch subscription for the CLI [as described in docs](https://docs.microsoft.com/en-us/cli/azure/manage-azure-subscriptions-azure-cli?view=azure-cli-latest).

**Comment by fouldsy** [comment]
For a lot of these scripts, yes, you're going to need to set a different subscription when you have multiple. That's not typically going to be the case if you use a separate free trial account to separate learning from existing work subscriptions. Getting into multiple subscriptions is definitely something that ends up happening in production, but as with a lot of things, is a tough balance to cover in the book without being able to actually show multiple subscriptions in use! Glad you were able to get it going though @arto-pihlaja 

I'm going to close out this actual issue since it's resolved in the 2nd edition version of the scripts.
